package: 
  name: epix_hr_core
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
   number: {{ GIT_DESCRIBE_NUMBER|int }}

requirements:
   build:
     - python
     - rogue
     - git
     - gitpython
     - numpy

   run:
     - python
     - rogue
     - numpy

about:
   home: https://github.com/slaclab/epix-hr-core
   license: SLAC Open License
   license_file: LICENSE.txt
   summary: epix-hr-core Firmware Library

